# Generated by Django 5.1.6 on 2025-02-15 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentnsn', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinalYearProject',
            fields=[
                ('roll_number', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='studentnsn.personalinformation')),
                ('project_title', models.CharField(max_length=50)),
                ('team_no', models.CharField(max_length=10)),
                ('guide_name', models.CharField(max_length=100)),
                ('team_leader', models.CharField(max_length=100)),
                ('team_members', models.TextField()),
                ('problem_statement', models.FileField(upload_to='documents/tFinalYear_Problem_statements/')),
            ],
            options={
                'db_table': 'project',
            },
        ),
        migrations.CreateModel(
            name='FinalYearProjectthesis',
            fields=[
                ('roll_number', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='studentnsn.personalinformation')),
                ('thesis', models.URLField()),
            ],
            options={
                'db_table': 'projectthesis',
            },
        ),
    ]
