# Generated by Django 5.1.6 on 2025-02-15 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffnsn', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentsattendance',
            name='semester',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], default='1', max_length=2),
        ),
    ]
